name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_script:
        description: 'Run the Python script'
        required: false
        default: 'false'
        type: boolean

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Cache pip dependencies
      id: cache-pip
      uses: actions/cache@v3
      with:
        path: venv
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      if: steps.cache-pip.outputs.cache-hit != 'true'
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify dependencies
      run: |
        source venv/bin/activate
        pip freeze

    - name: Run Python script
      if: github.event.inputs.run_script == 'true' || (github.event_name == 'push' || github.event_name == 'pull_request')
      run: |
        source venv/bin/activate
        python scripts/your_script.py
      continue-on-error: false  # 如果希望在脚本失败时停止工作流，可以设置为 false
